(use-modules (guix)
			 (guix packages)
			 (guix download)
			 (guix git-download)
			 (guix build-system meson)
			 (gnu packages python)
			 (gnu packages commencement)
			 (gnu packages gcc)
			 (gnu packages maths)
			 (gnu packages crypto)
			 (gnu packages sqlite)
			 (gnu packages check)
			 (gnu packages sdl)
			 (gnu packages base)
			 (gnu packages guile)
			 (gnu packages gettext)
			 (gnu packages linux)
			 (gnu packages vim)
			 (gnu packages pkg-config)
			 (gnu packages blitz)
			 (gnu packages magnum)
			 (gnu packages unistdx)
			 (gnu packages zxcvbn-c)
			 (gnu packages sqlitex)
			 (gnu packages ggg)
			 ((guix licenses) #:select (gpl3+)))

(package
  (name "ggg")
  (version "1.2.3")
  (source (origin
			(method url-fetch)
			(uri (string-append (getenv "HOME") "/repos/subordination/ggg"))
			(sha256 (base32 "1vyw795jxg7d9ac7hlybink0jgkrybjcbzh1gcq69ck4ggqc6bxn"))))
  (build-system meson-build-system)
  ;; https://issues.guix.info/issue/30756
  (arguments
	'(#:phases (modify-phases
				 %standard-phases
				 (add-before 'configure 'fix-paths
							 (lambda _
							   (unsetenv "C_INCLUDE_PATH")
							   (unsetenv "CPLUS_INCLUDE_PATH"))))))
  (inputs
    `(("unistdx" ,unistdx)
      ("zxcvbn-c" ,zxcvbn-c)
      ("sqlite" ,sqlite)
      ("sqlitex" ,sqlitex)
      ("ggg-crypt" ,ggg-crypt)
      ("guile-2.2" ,guile-2.2)
      ("linux-pam" ,linux-pam)
      ("libsodium" ,libsodium)))
  (native-inputs
    `(("googletest" ,googletest)
      ("gettext-minimal" ,gettext-minimal)
      ("pkg-config" ,pkg-config)))
  (synopsis "Groups of groups of groups")
  (description "NSS and PAM modules that support arbitrary nesting of users and groups.")
  (home-page "https://github.com/igankevich/ggg")
  (license gpl3+))
