(use-modules (guix)
			 (guix packages)
			 (guix download)
			 (guix git-download)
			 (guix build-system meson)
			 (gnu packages python)
			 (gnu packages commencement)
			 (gnu packages gcc)
			 (gnu packages maths)
			 (gnu packages sqlite)
			 (gnu packages check)
			 (gnu packages sdl)
			 (gnu packages base)
			 (gnu packages guile)
			 (gnu packages acl)
			 (gnu packages gettext)
			 (gnu packages linux)
			 (gnu packages vim)
			 (gnu packages pkg-config)
			 (stables blitz)
			 (stables magnum)
			 (stables unistdx)
			 (stables zxcvbn-c)
			 (stables sqlitex)
			 ((guix licenses) #:select (gpl3+)))

(package
  (name "ggg")
  (version "1.2.1")
  (source (origin
			(method url-fetch)
			(uri (string-append (getenv "HOME") "/repos/subordination/ggg"))
			(sha256 (base32 "1vyw795jxg7d9ac7hlybink0jgkrybjcbzh1gcq69ck4ggqc6bxn"))))
  (build-system meson-build-system)
  (inputs `(("unistdx" ,unistdx)
			("zxcvbn-c" ,zxcvbn-c)
			("sqlite" ,sqlite)
			("sqlitex" ,sqlitex)
			("guile-2.0" ,guile-2.0)
			("acl" ,acl)
			("linux-pam" ,linux-pam)))
  (native-inputs `(("googletest" ,googletest)
				   ("gettext-minimal" ,gettext-minimal)
				   ("gcc:lib" ,gcc-9 "lib")
				   ("gcc-toolchain" ,gcc-toolchain-9)
				   ("pkg-config" ,pkg-config)))
  (synopsis "Groups of groups of groups")
  (description "NSS and PAM modules that support arbitrary nesting of users and groups.")
  (home-page "https://github.com/igankevich/ggg")
  (license gpl3+))
