#!/bin/sh

overlay="$MESON_BUILD_ROOT/overlay"
myroot="$overlay/myroot"
workdir="$overlay/workdir"
newroot="$overlay/newroot"

# clean old root 
rm --preserve-root --one-file-system -rf "$overlay"

# install ggg
cd "$MESON_BUILD_ROOT"
meson configure -Dprefix=$myroot/usr -Dsysconfdir=/etc
ninja install

# install nsswitch
mkdir -p "$myroot/etc/ggg" "$newroot" "$workdir"
cat > "$myroot/etc/nsswitch.conf" << EOF
passwd: files ggg
shadow: files ggg
group: files ggg
#initgroups: files
EOF
